# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "web" do |web|
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "db"
  end

  config.vm.define "cache" do |cache|
    cache.vm.box = "ubuntu/kinetic64"
    cache.vm.hostname = "cache"
  end

  (1..4).each do |index|
    config.vm.define "server#{index}" do |server|
      server.vm.hostname = "server#{index}"

      server.vm.provider "virtualbox" do |vb|
        vb.name = "svr#{index}"
      end
    end
  end

end
