# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/kinetic64"

  config.vm.hostname = "webby"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: '127.0.0.1'

  config.vm.provider "virtualbox" do |vb|
    vb.name = "webby"
    vb.memory = 3072
    vb.cpus = 4
  end

  config.vm.provision "shell", name: "time", run: "always", path: "files/time.sh"

  config.vm.provision "shell", name: "ansible", privileged: false, path: "files/install.ansible.sh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansibles/playbook.yml"
  end

  config.vm.provision "shell", name: "dotfiles", privileged: false, inline:<<-DOTFILES

    echo alias bat="batcat" >> /home/vagrant/.bashrc
    touch /home/vagrant/.hushlogin
  
  DOTFILES


  config.vm.provision "shell", path: "files/install.nginx.sh"
  config.vm.provision "shell", name: "tools", path: "files/install.tools.sh"
  config.vm.provision "file", source: "files/index.html", destination: "$HOME/"
  config.vm.provision "shell", name: "html", path: "files/install.html.sh"

end
