# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.name = "webby"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: '127.0.0.1'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 3072
    vb.cpus = 4
  end
end
